server:
  port: 8999

spring:
  application:
    name: gataway-server

eureka:
  client:
    service-url:  #eureka的地址信息
      defaultZone: http://127.0.0.1:9999/eureka
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000